/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Registro;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.Juego;

/**
 *
 * @author matia
 */
public class AgregarJuego extends javax.swing.JFrame {

    /**
     * Creates new form AgregarJuego
     */
    public AgregarJuego() {
        initComponents();
        this.jbtn_salir.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbl_titulo = new javax.swing.JLabel();
        jlbl_programador = new javax.swing.JLabel();
        jlbl_publicacion = new javax.swing.JLabel();
        jlbl_precio = new javax.swing.JLabel();
        jlbl_disponible = new javax.swing.JLabel();
        jtxt_titulo = new javax.swing.JTextField();
        jtxt_programador = new javax.swing.JTextField();
        jtxt_dia = new javax.swing.JTextField();
        jtxt_precio = new javax.swing.JTextField();
        jchk_disponible = new javax.swing.JCheckBox();
        jtxt_mes = new javax.swing.JTextField();
        jtxt_año = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jbtn_enviar = new javax.swing.JButton();
        jbtn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Juegos");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jlbl_titulo.setText("Titulo:");

        jlbl_programador.setText("Programador:");

        jlbl_publicacion.setText("Publicación:");

        jlbl_precio.setText("Precio:");

        jlbl_disponible.setText("Disponible:");

        jtxt_titulo.setText("Ingrese Título");
        jtxt_titulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_tituloFocusGained(evt);
            }
        });
        jtxt_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_tituloActionPerformed(evt);
            }
        });

        jtxt_programador.setText("Ingrese Programador");
        jtxt_programador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_programadorFocusGained(evt);
            }
        });

        jtxt_dia.setText("dd");
        jtxt_dia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_diaFocusGained(evt);
            }
        });

        jtxt_precio.setText("Ingrese Precio");
        jtxt_precio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_precioFocusGained(evt);
            }
        });

        jtxt_mes.setText("mm");
        jtxt_mes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_mesFocusGained(evt);
            }
        });

        jtxt_año.setText("aaaa");
        jtxt_año.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_añoFocusGained(evt);
            }
        });
        jtxt_año.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_añoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addComponent(jtxt_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jtxt_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jtxt_año, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(109, 109, 109))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jlbl_precio)
                        .addComponent(jlbl_disponible))
                    .addGap(300, 300, 300)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbl_titulo)
                            .addComponent(jlbl_programador)
                            .addComponent(jlbl_publicacion))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxt_programador, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(jtxt_titulo)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jchk_disponible)
                        .addComponent(jtxt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_titulo)
                    .addComponent(jtxt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_programador)
                    .addComponent(jtxt_programador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_publicacion)
                    .addComponent(jtxt_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_precio)
                    .addComponent(jtxt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbl_disponible)
                    .addComponent(jchk_disponible))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jbtn_enviar.setText("Enviar");
        jbtn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_enviarActionPerformed(evt);
            }
        });

        jbtn_salir.setText("Salir");
        jbtn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jbtn_enviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_salir)
                .addGap(104, 104, 104))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_enviar)
                    .addComponent(jbtn_salir))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_tituloActionPerformed

    private void jtxt_añoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_añoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_añoActionPerformed

    private void jbtn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_enviarActionPerformed
            
        String titulo, programador, dia, mes, año, fechaStr;
        Date fecha = null;
        int precio = 0;
        boolean disponible;

        titulo = this.jtxt_titulo.getText();

        if (titulo.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Ingrese Titulo", "Validacion", 2);
            this.jtxt_titulo.requestFocus();
            return;

        }

        programador = this.jtxt_programador.getText();
        if (programador.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Ingrese Programador", "Validacion", 2);
            this.jtxt_programador.requestFocus();
            return;

        }
        dia = this.jtxt_dia.getText();
        mes = this.jtxt_mes.getText();
        año = this.jtxt_año.getText();

        if (dia.isEmpty() || mes.isEmpty() || año.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Ingrese Fecha", "Validacion", 2);
            this.jtxt_dia.requestFocus();
            return;

        }

        fechaStr = dia + "/" + mes + "/" + año;
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        try {
            fecha = formato.parse(fechaStr);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ingrese Fecha de formato dd/mm/yyyy", "Validacion", 2);
            this.jtxt_dia.requestFocus();
        }

        try {

            precio = Integer.parseInt(this.jtxt_precio.getText());

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El precio debe ser numerico", "Validacion", 2);
            this.jtxt_precio.requestFocus();
        }

        disponible = this.jchk_disponible.isSelected();
        Juego juego = new Juego(0, titulo, programador, precio, disponible, fecha);

        Registro reg = new Registro();
        if (reg.buscarJuego(reg.buscarTodos(), titulo) == false) {

            if (reg.agregar(juego)) {
                JOptionPane.showMessageDialog(this, "Se agrego Juego", "Informacion", 2);

            } else {
                JOptionPane.showMessageDialog(this, "No se agrego Juego", "Validacion", 2);
            }
        } else {

            JOptionPane.showMessageDialog(this, "El juego ya existe", "informacion", 2);

        }

    }//GEN-LAST:event_jbtn_enviarActionPerformed

    private void jtxt_tituloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_tituloFocusGained
            this.jtxt_titulo.setText("");
    }//GEN-LAST:event_jtxt_tituloFocusGained

    private void jtxt_programadorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_programadorFocusGained
        this.jtxt_programador.setText("");
    }//GEN-LAST:event_jtxt_programadorFocusGained

    private void jtxt_diaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_diaFocusGained
        this.jtxt_dia.setText("");
    }//GEN-LAST:event_jtxt_diaFocusGained

    private void jtxt_mesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_mesFocusGained
        this.jtxt_mes.setText("");
    }//GEN-LAST:event_jtxt_mesFocusGained

    private void jtxt_añoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_añoFocusGained
        this.jtxt_año.setText("");
    }//GEN-LAST:event_jtxt_añoFocusGained

    private void jtxt_precioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_precioFocusGained
        this.jtxt_precio.setText("");
    }//GEN-LAST:event_jtxt_precioFocusGained

    private void jbtn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_salirActionPerformed
        dispose();
    }//GEN-LAST:event_jbtn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AgregarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AgregarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AgregarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AgregarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AgregarJuego().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtn_enviar;
    private javax.swing.JButton jbtn_salir;
    private javax.swing.JCheckBox jchk_disponible;
    private javax.swing.JLabel jlbl_disponible;
    private javax.swing.JLabel jlbl_precio;
    private javax.swing.JLabel jlbl_programador;
    private javax.swing.JLabel jlbl_publicacion;
    private javax.swing.JLabel jlbl_titulo;
    private javax.swing.JTextField jtxt_año;
    private javax.swing.JTextField jtxt_dia;
    private javax.swing.JTextField jtxt_mes;
    private javax.swing.JTextField jtxt_precio;
    private javax.swing.JTextField jtxt_programador;
    private javax.swing.JTextField jtxt_titulo;
    // End of variables declaration//GEN-END:variables
}
